# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from typing import Any, Optional, Union

# Type alias for metadata values
MetadataValue = Union[int, float, str, list["MetadataValue"], dict[str, "MetadataValue"]]


class Node:
    """A node in the database hierarchy.

    Each node has a unique identifier, an optional parent reference,
    a count of its children, a name, and flexible metadata storage.

    Example:
        >>> node = Node(1, "root")
        >>> node.set_meta("version", 1)
        >>> print(node.get_meta("version"))
        1
    """

    def __new__(
        cls,
        id: int,
        name: str,
        parent_id: Optional[int] = None,
        children_count: int = 0,
        metadata: Optional[MetadataValue] = None,
    ) -> "Node":
        """Create a new Node.

        Args:
            id: Unique identifier for this node.
            name: The name of this node.
            parent_id: Optional ID of the parent node.
            children_count: Number of direct children (default: 0).
            metadata: Optional metadata (int, float, str, list, or dict).

        Returns:
            A new Node instance.

        Example:
            >>> node = Node(1, "root")
            >>> child = Node(2, "child", parent_id=1)
        """
        ...

    @property
    def id(self) -> int:
        """The unique identifier of this node."""
        ...

    @property
    def name(self) -> str:
        """The name of this node."""
        ...

    @property
    def parent_id(self) -> Optional[int]:
        """The ID of the parent node, or None if this is a root node."""
        ...

    @property
    def children_count(self) -> int:
        """The number of direct children this node has."""
        ...

    @property
    def metadata(self) -> MetadataValue:
        """The metadata associated with this node.

        Returns the metadata as a Python object (int, float, str, list, or dict).
        """
        ...

    def set_meta(self, key: str, value: MetadataValue) -> None:
        """Set a metadata value by key.

        If the current metadata is not a dict, it will be converted to one
        with the original value stored under the key "value".

        Args:
            key: The key under which to store the value.
            value: The value to store (int, float, str, list, or dict).

        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("count", 42)
            >>> node.set_meta("tags", ["rust", "python"])
        """
        ...

    def get_meta(self, key: str) -> Optional[MetadataValue]:
        """Get a metadata value by key.

        Args:
            key: The key to look up.

        Returns:
            The value if found, or None if the key doesn't exist
            or metadata is not a dict.

        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("version", 1)
            >>> node.get_meta("version")
            1
            >>> node.get_meta("missing") is None
            True
        """
        ...

    def to_json(self) -> str:
        """Convert the node to a JSON string.

        Returns:
            A JSON string representation of the node.

        Example:
            >>> node = Node(1, "root")
            >>> json_str = node.to_json()
        """
        ...

    def to_json_pretty(self) -> str:
        """Convert the node to a pretty-printed JSON string.

        Returns:
            A formatted JSON string representation of the node.
        """
        ...

    @staticmethod
    def from_json(json_str: str) -> "Node":
        """Create a Node from a JSON string.

        Args:
            json_str: A JSON string representing a node.

        Returns:
            A new Node instance.

        Raises:
            ValueError: If the JSON string is invalid.

        Example:
            >>> json_str = '{"id": 1, "name": "root", ...}'
            >>> node = Node.from_json(json_str)
        """
        ...

    def __repr__(self) -> str:
        """Get a string representation of the node."""
        ...


def get_version() -> str:
    """Get the version of the synapse_db library.

    Returns:
        The version string (e.g., "0.1.0").

    Example:
        >>> import synapse_db
        >>> synapse_db.get_version()
        '0.1.0'
    """
    ...
