# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class Edge:
    r"""
    An edge connecting two nodes in the graph.
    
    Edges use canonical ordering: node_a always has the smaller ID.
    The direction field tracks the logical direction of the edge.
    
    Example:
        >>> edge = Edge(1, 5, 2, "follows")  # Creates edge from node 5 to node 2
        >>> edge.node_a  # Always the smaller ID
        2
        >>> edge.node_b  # Always the larger ID
        5
        >>> edge.direction  # BtoA because 5 > 2, so original direction was B to A
        EdgeDirection.BtoA
    """
    id: int
    node_a: int
    node_b: int
    direction: synapse_db.EdgeDirection
    name: str
    metadata: typing.Any
    def __new__(cls,id,from_node,to_node,name,bidirectional = ...,metadata = ...): ...
    def set_meta(self, key:str, value:typing.Any) -> None:
        r"""
        Set a metadata value by key.
        
        Args:
            key: The key under which to store the value.
            value: The value to store (int, float, str, list, or dict).
        
        Example:
            >>> edge = Edge(1, 2, 3, "link")
            >>> edge.set_meta("weight", 1.5)
        """
        ...

    def get_meta(self, key:str) -> typing.Optional[typing.Any]:
        r"""
        Get a metadata value by key.
        
        Args:
            key: The key to look up.
        
        Returns:
            The value if found, or None if the key doesn't exist.
        
        Example:
            >>> edge.set_meta("weight", 1.5)
            >>> edge.get_meta("weight")
            1.5
        """
        ...

    def connects(self, node_id:int) -> bool:
        r"""
        Check if this edge connects the given node.
        
        Args:
            node_id: The node ID to check.
        
        Returns:
            True if this edge connects to the given node.
        
        Example:
            >>> edge = Edge(1, 2, 5, "link")
            >>> edge.connects(2)
            True
            >>> edge.connects(3)
            False
        """
        ...

    def connects_pair(self, x:int, y:int) -> bool:
        r"""
        Check if this edge connects both given nodes.
        
        Args:
            x: First node ID.
            y: Second node ID.
        
        Returns:
            True if this edge connects both nodes (in any order).
        
        Example:
            >>> edge = Edge(1, 2, 5, "link")
            >>> edge.connects_pair(2, 5)
            True
            >>> edge.connects_pair(5, 2)  # Order doesn't matter
            True
        """
        ...

    def allows_traversal(self, from_node:int, to_node:int) -> bool:
        r"""
        Check if traversal from one node to another is allowed.
        
        Args:
            from_node: The starting node ID.
            to_node: The target node ID.
        
        Returns:
            True if traversal is allowed based on edge direction.
        
        Example:
            >>> edge = Edge(1, 2, 5, "follows")  # Directed: 2 -> 5
            >>> edge.allows_traversal(2, 5)
            True
            >>> edge.allows_traversal(5, 2)
            False
        """
        ...

    def __repr__(self) -> str:
        r"""
        Get a string representation of the edge.
        """
        ...

    def to_json(self) -> str:
        r"""
        Convert the edge to a JSON string.
        """
        ...

    def to_json_pretty(self) -> str:
        r"""
        Convert the edge to a pretty-printed JSON string.
        """
        ...

    @staticmethod
    def from_json(json_str:str) -> Edge:
        r"""
        Create an Edge from a JSON string.
        
        Args:
            json_str: A JSON string representing an edge.
        
        Returns:
            A new Edge instance.
        
        Raises:
            ValueError: If the JSON string is invalid.
        """
        ...


class Node:
    r"""
    A node in the database hierarchy.
    
    Each node has a unique identifier, an optional parent reference,
    a count of its children, a name, and flexible metadata storage.
    
    Example:
        >>> node = Node(1, "root")
        >>> node.set_meta("version", 1)
        >>> print(node.get_meta("version"))
        1
    """
    id: int
    name: str
    parent_id: typing.Optional[int]
    children_count: int
    metadata: typing.Any
    def __new__(cls,id,name,parent_id = ...,children_count = ...,metadata = ...): ...
    def set_meta(self, key:str, value:typing.Any) -> None:
        r"""
        Set a metadata value by key.
        
        If the current metadata is not a dict, it will be converted to one
        with the original value stored under the key "value".
        
        Args:
            key: The key under which to store the value.
            value: The value to store (int, float, str, list, or dict).
        
        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("count", 42)
            >>> node.set_meta("tags", ["rust", "python"])
        """
        ...

    def get_meta(self, key:str) -> typing.Optional[typing.Any]:
        r"""
        Get a metadata value by key.
        
        Args:
            key: The key to look up.
        
        Returns:
            The value if found, or None if the key doesn't exist
            or metadata is not a dict.
        
        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("version", 1)
            >>> node.get_meta("version")
            1
            >>> node.get_meta("missing") is None
            True
        """
        ...

    def __repr__(self) -> str:
        r"""
        Get a string representation of the node.
        """
        ...

    def to_json(self) -> str:
        r"""
        Convert the node to a JSON string.
        
        Returns:
            A JSON string representation of the node.
        
        Example:
            >>> node = Node(1, "root")
            >>> json_str = node.to_json()
        """
        ...

    def to_json_pretty(self) -> str:
        r"""
        Convert the node to a pretty-printed JSON string.
        
        Returns:
            A formatted JSON string representation of the node.
        """
        ...

    @staticmethod
    def from_json(json_str:str) -> Node:
        r"""
        Create a Node from a JSON string.
        
        Args:
            json_str: A JSON string representing a node.
        
        Returns:
            A new Node instance.
        
        Raises:
            ValueError: If the JSON string is invalid.
        
        Example:
            >>> json_str = '{"id": 1, "name": "root", ...}'
            >>> node = Node.from_json(json_str)
        """
        ...


def get_version() -> str:
    r"""
    Get the version of the synapse_db library.
    
    Returns:
        The version string (e.g., "0.1.0").
    
    Example:
        >>> import synapse_db
        >>> synapse_db.get_version()
        '0.1.0'
    """
    ...

