# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class Node:
    r"""
    A node in the database hierarchy.
    
    Each node has a unique identifier, an optional parent reference,
    a count of its children, a name, and flexible metadata storage.
    
    Example:
        >>> node = Node(1, "root")
        >>> node.set_meta("version", 1)
        >>> print(node.get_meta("version"))
        1
    """
    id: int
    name: str
    parent_id: typing.Optional[int]
    children_count: int
    metadata: typing.Any
    def __new__(cls,id,name,parent_id = ...,children_count = ...,metadata = ...): ...
    def set_meta(self, key:str, value:typing.Any) -> None:
        r"""
        Set a metadata value by key.
        
        If the current metadata is not a dict, it will be converted to one
        with the original value stored under the key "value".
        
        Args:
            key: The key under which to store the value.
            value: The value to store (int, float, str, list, or dict).
        
        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("count", 42)
            >>> node.set_meta("tags", ["rust", "python"])
        """
        ...

    def get_meta(self, key:str) -> typing.Optional[typing.Any]:
        r"""
        Get a metadata value by key.
        
        Args:
            key: The key to look up.
        
        Returns:
            The value if found, or None if the key doesn't exist
            or metadata is not a dict.
        
        Example:
            >>> node = Node(1, "example")
            >>> node.set_meta("version", 1)
            >>> node.get_meta("version")
            1
            >>> node.get_meta("missing") is None
            True
        """
        ...

    def __repr__(self) -> str:
        r"""
        Get a string representation of the node.
        """
        ...

    def to_json(self) -> str:
        r"""
        Convert the node to a JSON string.
        
        Returns:
            A JSON string representation of the node.
        
        Example:
            >>> node = Node(1, "root")
            >>> json_str = node.to_json()
        """
        ...

    def to_json_pretty(self) -> str:
        r"""
        Convert the node to a pretty-printed JSON string.
        
        Returns:
            A formatted JSON string representation of the node.
        """
        ...

    @staticmethod
    def from_json(json_str:str) -> Node:
        r"""
        Create a Node from a JSON string.
        
        Args:
            json_str: A JSON string representing a node.
        
        Returns:
            A new Node instance.
        
        Raises:
            ValueError: If the JSON string is invalid.
        
        Example:
            >>> json_str = '{"id": 1, "name": "root", ...}'
            >>> node = Node.from_json(json_str)
        """
        ...


def get_version() -> str:
    r"""
    Get the version of the synapse_db library.
    
    Returns:
        The version string (e.g., "0.1.0").
    
    Example:
        >>> import synapse_db
        >>> synapse_db.get_version()
        '0.1.0'
    """
    ...

